2019-09-17 16:37:36,527 INFO: MyBlog startup [in /Users/antonpetrov/coding/Python/blog/app/error.py:47]
2019-09-17 16:37:51,218 ERROR: Exception on /reset_password_request [POST] [in /Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/antonpetrov/coding/Python/blog/app/routs.py", line 171, in reset_password_request
    send_password_reset_email(user)
  File "/Users/antonpetrov/coding/Python/blog/app/email.py", line 21, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2019-09-17 16:38:24,778 ERROR: Exception on /reset_password_request [POST] [in /Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/antonpetrov/coding/Python/blog/app/routs.py", line 171, in reset_password_request
    send_password_reset_email(user)
  File "/Users/antonpetrov/coding/Python/blog/app/email.py", line 21, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2019-09-17 16:38:51,510 ERROR: Exception on /reset_password_request [POST] [in /Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/antonpetrov/coding/Python/blog/app/routs.py", line 171, in reset_password_request
    send_password_reset_email(user)
  File "/Users/antonpetrov/coding/Python/blog/app/email.py", line 21, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2019-09-17 16:41:51,159 INFO: MyBlog startup [in /Users/antonpetrov/coding/Python/blog/app/error.py:47]
2019-09-17 16:42:08,353 ERROR: Exception on /reset_password_request [POST] [in /Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/antonpetrov/coding/Python/blog/app/routs.py", line 171, in reset_password_request
    send_password_reset_email(user)
  File "/Users/antonpetrov/coding/Python/blog/app/email.py", line 22, in send_password_reset_email
    sender=app.config['ADMINS'][0],
AttributeError: module 'app' has no attribute 'config'
2019-09-17 16:47:21,029 INFO: MyBlog startup [in /Users/antonpetrov/coding/Python/blog/app/error.py:47]
2019-09-17 16:47:34,376 ERROR: Exception on /reset_password_request [POST] [in /Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/antonpetrov/coding/Python/blog/app/routs.py", line 171, in reset_password_request
    send_password_reset_email(user)
  File "/Users/antonpetrov/coding/Python/blog/app/email.py", line 27, in send_password_reset_email
    user=user, token=token),
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2019-09-17 16:48:25,942 INFO: MyBlog startup [in /Users/antonpetrov/coding/Python/blog/app/error.py:47]
2019-09-17 16:48:36,195 ERROR: Exception on /reset_password_request [POST] [in /Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/antonpetrov/coding/Python/blog/app/routs.py", line 171, in reset_password_request
    send_password_reset_email(user)
  File "/Users/antonpetrov/coding/Python/blog/app/email.py", line 27, in send_password_reset_email
    user=user, token=token),
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2019-09-17 16:52:41,342 INFO: MyBlog startup [in /Users/antonpetrov/coding/Python/blog/app/error.py:47]
2019-09-17 16:52:59,227 ERROR: Exception on /reset_password_request [POST] [in /Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/antonpetrov/coding/Python/blog/app/routs.py", line 171, in reset_password_request
    send_password_reset_email(user)
  File "/Users/antonpetrov/coding/Python/blog/app/email.py", line 27, in send_password_reset_email
    user=user, token=token),
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: app/email/reset_password.txt2019-09-17 17:12:03,677 INFO: MyBlog startup [in /Users/antonpetrov/coding/Python/blog/app/error.py:47]
2019-09-17 17:12:14,432 ERROR: Exception on /reset_password_request [POST] [in /Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/antonpetrov/coding/Python/blog/app/routs.py", line 171, in reset_password_request
    send_password_reset_email(user)
  File "/Users/antonpetrov/coding/Python/blog/app/email.py", line 27, in send_password_reset_email
    user=user, token=token),
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/antonpetrov/coding/Python/blog/venv/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /Users/antonpetrov/coding/Python/blog/app/email/reset_password.txt
2019-09-17 17:16:15,755 INFO: MyBlog startup [in /Users/antonpetrov/coding/Python/blog/app/error.py:47]
2019-09-17 17:25:25,951 INFO: MyBlog startup [in /Users/antonpetrov/coding/Python/blog/app/error.py:47]
